POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfMkBnbWFpbC5jb20iLCJleHAiOjE3MzMwMzQ5NDYsInVzZXJJZCI6Mn0.I-pQyAlTgA2wT5pdSKlgLmGuSfhV9XJz-m94fD7P5KI

{
    "name": "Test event 3",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2024-01-01T15:30:00.000Z"
}