PUT http://localhost:8080/events/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfMkBnbWFpbC5jb20iLCJleHAiOjE3MzM3NjE1MjUsInVzZXJJZCI6Mn0.gbn7IWy0wScUttukxLTGxq_z2v5RK9Hc9bnMlNvmkUo



{
    "name": "Test event update",
    "description": "A test event update",
    "location": "A test location update",
    "dateTime": "2025-01-01T15:30:00.000Z"
} 